-- Run this in the Supabase SQL Editor

-- 1. Create 'exams' table
create table public.exams (
  id bigint generated by default as identity primary key,
  access_code text not null unique,
  exam_name text not null,
  google_form_url text not null,
  is_active boolean default true,
  strict_mode boolean default true,
  duration integer default 60, -- Exam duration in minutes
  target_class text default 'ALL', -- 'ALL', '9A', '9B', etc.
  session_type text default 'ALL', -- 'ALL', 'ODD', 'EVEN'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Create 'cheat_logs' table
create table public.cheat_logs (
  id bigint generated by default as identity primary key,
  student_name text not null,
  exam_access_code text not null,
  violation_type text not null,
  details text,
  student_class text, -- "9A"
  student_absen text, -- "12"
  timestamp timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Enable Row Level Security (RLS)
alter table public.exams enable row level security;
alter table public.cheat_logs enable row level security;

-- 4. Create Policies

-- POLICY: Exams
-- Students (Anon) can read exams only if they know the access_code (We filter this in client, but RLS allows read for all for simplicity in this prototype, OR we can restrict).
-- Better approach: Allow read for everyone, app logic filters.
create policy "Enable read access for all users" on public.exams for select using (true);

-- Teachers (Authenticated) can insert/update/delete
create policy "Teachers can do everything on exams" on public.exams for all using (auth.role() = 'authenticated');


-- POLICY: Cheat Logs
-- Students (Anon) can INSERT logs (logging their own cheats)
create policy "Students can insert logs" on public.cheat_logs for insert with check (true);

-- Teachers (Authenticated) can SELECT logs
create policy "Teachers can view logs" on public.cheat_logs for select using (auth.role() = 'authenticated');

-- OPTIONAL: Create a 'Teacher' user bucket if you want to invite them via email, 
-- or just use the default Supabase Auth -> Users panel.
